name: BUILD
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "8"
      - name: build
        working-directory: core/boot
        run: |
          ..\..\gradlew clean build
